aljarafe:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: True
  
asomadilla:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: True
  
aljarafe:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: True

asomadilla:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: True

bermejales:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: True

rondadelvalle:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: True

torneo:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: True