aljarafe0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

asomadilla0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

bermejales0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

rondadelvalle0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

torneo0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

# aljarafe:
#   seq_len:
#     - 24
#     - 72
#   pred_len: 24
#   shift: 24
#   crossval: True
  
# asomadilla:
#   seq_len:
#     - 24
#     - 72
#   pred_len: 24
#   shift: 24
#   crossval: True

# vidjerez:
#   seq_len:
#     - 2
#     - 5
#   pred_len: 1
#   shift: 1
#   crossval: False

# vidjerezlobes:
#   seq_len:
#     - 2
#     - 5
#   pred_len: 1
#   shift: 1
#   crossval: False
