aljarafe0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

asomadilla0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

bermejales0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

rondadelvalle0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

torneo0523:
  seq_len:
    - 24
    - 72
  pred_len: 24
  shift: 24
  crossval: False

